#pragma once

enum ComputerAreaLockedScreen_t
{
	COMPUTER_LOCKED_DOWNLOAD,
	COMPUTER_LOCKED_SECURITY_CAM_1,
	COMPUTER_LOCKED_SECURITY_CAM_2,
	COMPUTER_LOCKED_SECURITY_CAM_3,
	COMPUTER_LOCKED_TURRET_1,
	COMPUTER_LOCKED_TURRET_2,
	COMPUTER_LOCKED_TURRET_3,
	COMPUTER_LOCKED_MAIL,
	COMPUTER_LOCKED_MAIL_1,
	COMPUTER_LOCKED_MAIL_2,
	COMPUTER_LOCKED_MAIL_3,
	COMPUTER_LOCKED_MAIL_4,
	COMPUTER_LOCKED_NEWS,
	COMPUTER_LOCKED_STOCKS,
	COMPUTER_LOCKED_WEATHER,
	COMPUTER_LOCKED_PLANT,
	COMPUTER_LOCKED_CUSTOM_SCREEN_1,
	COMPUTER_LOCKED_CUSTOM_SCREEN_2,
	COMPUTER_LOCKED_CUSTOM_SCREEN_3,
	COMPUTER_LOCKED_CUSTOM_SCREEN_4,
	COMPUTER_LOCKED_CUSTOM_SCREEN_5,
	COMPUTER_LOCKED_CUSTOM_SCREEN_6,
	COMPUTER_LOCKED_SCREEN_NUM_BITS,
};
