#pragma once

#ifdef RD_7A_DROPS
#include "steam/isteaminventory.h"

enum RD_Crafting_Material_t
{
	// common
	RD_CRAFTING_MATERIAL_SCRAP_METAL,
	RD_CRAFTING_MATERIAL_ELECTRICAL_COMPONENTS,
	RD_CRAFTING_MATERIAL_SPARE_PIPE,
	RD_CRAFTING_MATERIAL_PLASTICS,
	RD_CRAFTING_MATERIAL_COOLANT,
	RD_CRAFTING_MATERIAL_MINI_CRATE,
	RD_CRAFTING_MATERIAL_BATTERY_PACK,

	// ultra-common
	RD_CRAFTING_MATERIAL_LOOSE_WIRES,
	RD_CRAFTING_MATERIAL_CARBON,

	// uncommon
	RD_CRAFTING_MATERIAL_ALIEN_CHITIN,
	RD_CRAFTING_MATERIAL_BIOMASS_SAMPLE,
	RD_CRAFTING_MATERIAL_GLOWING_GREEN_ACID,
	RD_CRAFTING_MATERIAL_CLAW_FRAGMENT,

	// rare
	RD_CRAFTING_MATERIAL_MEMORY_MANAGEMENT_UNIT,
	RD_CRAFTING_MATERIAL_ARITHMETIC_LOGIC_UNIT,
	RD_CRAFTING_MATERIAL_DATA_STORAGE_MEDIUM,

	// regional
	RD_CRAFTING_MATERIAL_PILE_OF_RED_SAND,
	RD_CRAFTING_MATERIAL_ANTLION_CARAPACE,
	RD_CRAFTING_MATERIAL_CORROSIVE_FLUID_SAMPLE,
	RD_CRAFTING_MATERIAL_COOLED_VOLCANIC_ROCK,
	RD_CRAFTING_MATERIAL_RETRIEVED_DOCUMENTS,
	RD_CRAFTING_MATERIAL_UNOPENED_SYNUP_COLA,
	RD_CRAFTING_MATERIAL_ROLL_OF_VENT_TAPE,
	RD_CRAFTING_MATERIAL_ISOTOPES,
	RD_CRAFTING_MATERIAL_CRYOTIC,
	RD_CRAFTING_MATERIAL_ARGON_CANISTER,

	NUM_RD_CRAFTING_MATERIAL_TYPES,
};

enum RD_Crafting_Material_Rarity_t
{
	RD_CRAFTING_MATERIAL_RARITY_COMMON,
	RD_CRAFTING_MATERIAL_RARITY_ULTRA_COMMON,
	RD_CRAFTING_MATERIAL_RARITY_UNCOMMON,
	RD_CRAFTING_MATERIAL_RARITY_RARE,
	RD_CRAFTING_MATERIAL_RARITY_REGIONAL,
};

struct RD_Crafting_Material_Info
{
	const char *m_szName;
	SteamItemDef_t m_iTokenDef;
	SteamItemDef_t m_iRedeemDef;
	SteamItemDef_t m_iItemDef;
	RD_Crafting_Material_Rarity_t m_iRarity;

	const char *m_szModelName;
};

extern const RD_Crafting_Material_Info g_RD_Crafting_Material_Info[NUM_RD_CRAFTING_MATERIAL_TYPES];
#endif
