$modelname swarm/marine/attachments/night_vision.mdl
$cdmaterials models/player/male
$body equip "marine_night_vision.smd"

$texturegroup skinfamilies
{
	{ "medic_body" "medic_helmet" }
	{ "officer_body" "officer_helmet" }
	{ "medic_body" "medic_helmet" }
	{ "special_weapons_body" "special_weapons_helmet" }
	{ "tech_body" "tech_helmet" }
}

$sequence BindPose "marine_night_vision.smd"
$contents solid
$surfaceprop armorflesh
$opaque
