"Resource/UI/BaseModUI/ReactiveDropChallengeSelection.res"
{
	"ReactiveDropChallengeSelection"
	{
		"ControlName"	"Frame"
		"fieldName"		"ReactiveDropChallengeSelection"

		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"50"
		"wide"			"f0"
		"tall"			"f0"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
	}

	"Title"
	{
		"fieldName"			"Title"
		"xpos"				"c-266"
		"ypos"				"56"
		"wide"				"150"
		"tall"				"19"
		"zpos"				"5"
		"font"				"DefaultExtraLarge"
		"textAlignment"		"west"
		"ControlName"		"Label"
		"labelText"			"#rd_challenge_selection_title"
		"fgcolor_override"	"224 224 224 255"
	}

	"Divider1"
	{
		"ControlName"			"ImagePanel"
		"fieldName"				"Divider1"
		"xpos"					"c-238"
		"ypos"					"115"
		"zpos"					"2"
		"wide"					"450"
		"tall"					"2"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"image"					"divider_gradient"
		"scaleImage"			"1"
	}

	"TxtSearch"
	{
		"ControlName"			"ReactiveDropChallengeSelectionSearch"
		"fieldName"				"TxtSearch"
		"xpos"					"c-226"
		"ypos"					"88"
		"wide"					"160"
		"tall"					"15"
		"visible"				"1"
		"enabled"				"1"
	}

	"GplChallenges"
	{
		"ControlName"			"GenericPanelList"
		"fieldName"				"GplChallenges"
		"xpos"					"c-226"
		"ypos"					"115"
		"wide"					"450"
		"tall"					"185"
		"zpos"					"1"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"1"
		"proportionalToParent"	"1"

		"bgcolor_override"		"0 0 0 128"
	}

	"Divider2"
	{
		"ControlName"			"ImagePanel"
		"fieldName"				"Divider2"
		"xpos"					"c-238"
		"ypos"					"297"
		"zpos"					"2"
		"wide"					"450"
		"tall"					"2"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"tabPosition"			"0"
		"image"					"divider_gradient"
		"scaleImage"			"1"
	}

	"LblName"
	{
		"ControlName"		"Label"
		"fieldName"			"LblName"
		"xpos"				"c-140"
		"ypos"				"315"
		"wide"				"265"
		"tall"				"18"
		"zpos"				"1"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"font"				"DefaultLarge"
		"textAlignment"		"north-west"
	}

	"LblAuthor"
	{
		"ControlName"		"Label"
		"fieldName"			"LblAuthor"
		"xpos"				"c+45"
		"ypos"				"337"
		"wide"				"180"
		"tall"				"15"
		"zpos"				"1"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"Font"				"DefaultMedium"
		"textAlignment"		"north-east"
		"wrap"				"0"
		"dulltext"			"1"
	}

	"LblDescription"
	{
		"ControlName"		"Label"
		"fieldName"			"LblDescription"
		"xpos"				"c-140"
		"ypos"				"355"
		"zpos"				"1"
		"wide"				"365"
		"tall"				"75"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"Font"				"Default"
		"textAlignment"		"north-west"
		"wrap"				"1"
		"brighttext"		"1"
		"dulltext"			"0"
	}

	"ImgIcon"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"ImgIcon"
		"xpos"				"c-280"
		"ypos"				"315"
		"zpos"				"1"
		"wide"				"123"
		"tall"				"69"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"scaleImage"		"1"
	}

	"BackButton"
	{
		"ControlName"			"CNB_Button"
		"fieldName"				"BackButton"
		"xpos"					"c-264"
		"ypos"					"r23"
		"wide"					"117"
		"tall"					"27"
		"zpos"					"1"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"labelText"				"#nb_back"
		"command"				"BackButton"
		"textAlignment"			"center"
		"font"					"DefaultMedium"
		"fgcolor_override"		"113 142 181 255"
	}
}
