"Resource/UI/basemodui/nb_lobby_laser_rgb_menu.res"
{
	"Background"
	{
		"fieldName"		"Background"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"319"
		"tall"		"76"
		"ControlName"		"Panel"
//		"PaintBackgroundType"		"0"
//		"bgcolor_override"		"0 0 0 253"
		"image"			"swarm/color/color_highlight"
		"scaleImage"	"1"
		"zpos"		"0"
	}

	"Select_LaserColor_Panel"
	{
		"fieldName"		"Select_LaserColor_Panel"
		"ControlName"		"EditablePanel"
		"xpos"		"160"
		"ypos"		"70"
		"wide"		"319"
		"tall"		"76"
		"zpos"		"50"
	}
	"HSVSquare"
	{
		"fieldName"		"HSVSquare"
		"xpos"		"77"
		"ypos"		"5"
		"wide"		"125"
		"tall"		"64"
		"image"			"swarm\color\hsv_square"
		"ControlName"		"Panel"
		"scaleImage"	"1"
		"zpos"		"1"
	}
	"LaserPreviewButton"
	{
		"fieldName"		"LaserPreviewButton"
		"xpos"		"5"
		"ypos"		"5"
		"wide"		"64"
		"tall"		"64"
		"ControlName"		"CBitmapButton"
		"image"		"briefing/weapon_extra_silhouette"
// 		"pin_to_sibling"		"WeaponButton1"
// 		"pin_corner_to_sibling"		"0"
// 		"pin_to_sibling_corner"		"1"
		"zpos"		"5"
	}
	"LaserPreviewOverlayButton"
	{
		"fieldName"		"LaserPreviewOverlayButton"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"75"
		"tall"		"75"
		"ControlName"		"CBitmapButton"
		"image"		"swarm\color\laser_icon"
		"scaleImage"		"1"
// 		"pin_to_sibling"		"WeaponButton1"
// 		"pin_corner_to_sibling"		"0"
// 		"pin_to_sibling_corner"		"1"
		"zpos"		"6"
	}
	"HSVSlider"
	{
		"fieldName"		"HSVSlider"
		"xpos"		"209"
		"ypos"		"5"
		"wide"		"10"
		"tall"		"64"
		"ControlName"		"Panel"
		"image"		"swarm\color\hsv_slider_bar"
		"scaleImage"		"1"
		"zpos"		"5"
	}
	"HSVSquareMarker"
	{
		"fieldName"		"HSVSquareMarker"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"25"
		"tall"		"25"
		"ControlName"		"Panel"
		"image"		"swarm\color\hsv_square_marker"
		"scaleImage"		"1"
		"zpos"		"5"
	}
	"HSVSquareSliderMarker"
	{
		"fieldName"		"HSVSquareSliderMarker"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"25"
		"tall"		"25"
		"ControlName"		"Panel"
		"image"		"swarm\color\hsv_slider_marker"
		"scaleImage"		"1"
		"zpos"		"6"
	}
	"ActivateReplaceColorButton"
	{
		"fieldName"		"ActivateReplaceColorButton"
		"xpos"		"226"
		"ypos"		"5"
		"wide"		"15"
		"tall"		"64"
		"ControlName"		"Panel"
		"image"		"swarm\color\hsv_slider_bar"
		"scaleImage"		"1"
		"zpos"		"5"
	}
	"Color1Button"
	{
		"fieldName"		"Color1Button"
		"xpos"		"248"
		"ypos"		"5"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
		"scaleImage"		"1"
	}
	"Color2Button"
	{
		"fieldName"		"Color2Button"
		"xpos"		"271"
		"ypos"		"5"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
		"scaleImage"		"1"
	}
	"Color3Button"
	{
		"fieldName"		"Color3Button"
		"xpos"		"294"
		"ypos"		"5"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
		"scaleImage"		"1"
	}
	"Color4Button"
	{
		"fieldName"		"Color4Button"
		"xpos"		"248"
		"ypos"		"29"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
		"scaleImage"		"1"
	}
	"Color5Button"
	{
		"fieldName"		"Color5Button"
		"xpos"		"271"
		"ypos"		"29"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
		"scaleImage"		"1"
	}
	"Color6Button"
	{
		"fieldName"		"Color6Button"
		"xpos"		"294"
		"ypos"		"29"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
		"scaleImage"		"1"
	}
	"Color7Button"
	{
		"fieldName"		"Color7Button"
		"xpos"		"248"
		"ypos"		"53"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
		"scaleImage"		"1"
	}
	"Color8Button"
	{
		"fieldName"		"Color8Button"
		"xpos"		"271"
		"ypos"		"53"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
		"scaleImage"		"1"
	}
	"Color9Button"
	{
		"fieldName"		"Color9Button"
		"xpos"		"294"
		"ypos"		"53"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
		"scaleImage"		"1"
	}
	"Color1Highlight"
	{
		"fieldName"		"Color1Highlight"
		"xpos"		"247"
		"ypos"		"4"
		"wide"		"17"
		"tall"		"17"
		"image" 	"swarm\color\behind_color_highlight"
		"ControlName"		"Panel"
		"zpos"		"4"
		"scaleImage"		"1"
	}
	"Color2Highlight"
	{
		"fieldName"		"Color2Highlight"
		"xpos"		"270"
		"ypos"		"4"
		"wide"		"17"
		"tall"		"17"
		"image" 	"swarm\color\behind_color_highlight"
		"ControlName"		"Panel"
		"zpos"		"4"
		"scaleImage"		"1"
	}
	"Color3Highlight"
	{
		"fieldName"		"Color3Highlight"
		"xpos"		"293"
		"ypos"		"4"
		"wide"		"17"
		"tall"		"17"
		"image" 	"swarm\color\behind_color_highlight"
		"ControlName"		"Panel"
		"zpos"		"4"
		"scaleImage"		"1"
	}
	"Color4Highlight"
	{
		"fieldName"		"Color4Highlight"
		"xpos"		"247"
		"ypos"		"28"
		"wide"		"17"
		"tall"		"17"
		"image" 	"swarm\color\behind_color_highlight"
		"ControlName"		"Panel"
		"zpos"		"4"
		"scaleImage"		"1"
	}
	"Color5Highlight"
	{
		"fieldName"		"Color5Highlight"
		"xpos"		"270"
		"ypos"		"28"
		"wide"		"17"
		"tall"		"17"
		"image" 	"swarm\color\behind_color_highlight"
		"ControlName"		"Panel"
		"zpos"		"4"
		"scaleImage"		"1"
	}
	"Color6Highlight"
	{
		"fieldName"		"Color6Highlight"
		"xpos"		"293"
		"ypos"		"28"
		"wide"		"17"
		"tall"		"17"
		"image" 	"swarm\color\behind_color_highlight"
		"ControlName"		"Panel"
		"zpos"		"4"
		"scaleImage"		"1"
	}
	"Color7Highlight"
	{
		"fieldName"		"Color7Highlight"
		"xpos"		"247"
		"ypos"		"52"
		"wide"		"17"
		"tall"		"17"
		"image" 	"swarm\color\behind_color_highlight"
		"ControlName"		"Panel"
		"zpos"		"4"
		"scaleImage"		"1"
	}
	"Color8Highlight"
	{
		"fieldName"		"Color8Highlight"
		"xpos"		"270"
		"ypos"		"52"
		"wide"		"17"
		"tall"		"17"
		"image" 	"swarm\color\behind_color_highlight"
		"ControlName"		"Panel"
		"zpos"		"4"
		"scaleImage"		"1"
	}
	"Color9Highlight"
	{
		"fieldName"		"Color9Highlight"
		"xpos"		"293"
		"ypos"		"52"
		"wide"		"17"
		"tall"		"17"
		"image" 	"swarm\color\behind_color_highlight"
		"ControlName"		"Panel"
		"zpos"		"4"
		"scaleImage"		"1"
	}

	"HSVPreviewHighlight"
	{
		"fieldName"		"HSVPreviewHighlight"
		"xpos"		"265"
		"ypos"		"0"
		"wide"		"17"
		"tall"		"17"
		"image" 	"swarm\color\behind_color_highlight"
		"ControlName"		"Panel"
		"zpos"		"1"
		"scaleImage"		"1"
	}
	"HSVSquareHighlight"
	{
		"fieldName"		"HSVSquareHighlight"
		"xpos"		"265"
		"ypos"		"0"
		"wide"		"17"
		"tall"		"17"
		"image" 	"swarm\color\behind_color_highlight"
		"ControlName"		"Panel"
		"zpos"		"1"
		"scaleImage"		"1"
	}
	"HSVSliderHighlight"
	{
		"fieldName"		"HSVSliderHighlight"
		"xpos"		"265"
		"ypos"		"0"
		"wide"		"17"
		"tall"		"17"
		"image" 	"swarm\color\behind_color_highlight"
		"ControlName"		"Panel"
		"zpos"		"1"
		"scaleImage"		"1"
	}
	"ActivateReplaceColorHighlight"
	{
		"fieldName"		"ActivateReplaceColorHighlight"
		"xpos"		"265"
		"ypos"		"0"
		"wide"		"17"
		"tall"		"17"
		"image" 	"swarm\color\behind_color_highlight"
		"ControlName"		"Panel"
		"zpos"		"1"
		"scaleImage"		"1"
	}
}