"Resource/UI/basemodui/nb_lobby_laser_rgb_menu.res"
{
	"Background"
	{
		"fieldName"		"Background"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"319"
		"tall"		"76"
		"ControlName"		"Panel"
		"PaintBackgroundType"		"0"
		"bgcolor_override"		"0 0 0 253"
		"image"			"briefing/lobby_row_bg"
		"scaleImage"	"1"
		"zpos"		"0"
	}

	"Select_LaserColor_Panel"
	{
		"fieldName"		"Select_LaserColor_Panel"
		"ControlName"		"EditablePanel"
		"xpos"		"160"
		"ypos"		"70"
		"wide"		"319"
		"tall"		"76"
		"zpos"		"50"
	}
	"HSVSquare"
	{
		"fieldName"		"HSVSquare"
//		"xpos"		"75"
//		"ypos"		"0"
//		"wide"		"150"
//		"tall"		"75"
		"xpos"		"75"
		"ypos"		"0"
		"wide"		"150"
		"tall"		"75"
		"image"			"swarm\color\hsv_square"
		"ControlName"		"Panel"
		"scaleImage"	"1"
		"zpos"		"1"
	}
	"LaserPreviewButton"
	{
		"fieldName"		"LaserPreviewButton"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"75"
		"tall"		"75"
		"ControlName"		"CBitmapButton"
		"image"		"briefing/weapon_extra_silhouette"
// 		"pin_to_sibling"		"WeaponButton1"
// 		"pin_corner_to_sibling"		"0"
// 		"pin_to_sibling_corner"		"1"
		"zpos"		"5"
	}
	"LaserPreviewOverlayButton"
	{
		"fieldName"		"LaserPreviewOverlayButton"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"75"
		"tall"		"75"
		"ControlName"		"CBitmapButton"
		"image"		"swarm\color\laser_icon"
// 		"pin_to_sibling"		"WeaponButton1"
// 		"pin_corner_to_sibling"		"0"
// 		"pin_to_sibling_corner"		"1"
		"zpos"		"6"
	}
	"HSVSlider"
	{
		"fieldName"		"HSVSlider"
		"xpos"		"225"
		"ypos"		"0"
		"wide"		"10"
		"tall"		"75"
		"ControlName"		"Panel"
		"image"		"swarm\color\hsv_slider_bar"
		"scaleImage"		"1"
		"zpos"		"5"
	}
	"HSVSquareMarker"
	{
		"fieldName"		"HSVSquareMarker"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"25"
		"tall"		"25"
		"ControlName"		"Panel"
		"image"		"swarm\color\hsv_square_marker"
		"scaleImage"		"1"
		"zpos"		"5"
	}
	"HSVSquareSliderMarker"
	{
		"fieldName"		"HSVSquareSliderMarker"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"25"
		"tall"		"25"
		"ControlName"		"Panel"
		"image"		"swarm\color\hsv_slider_marker"
		"scaleImage"		"1"
		"zpos"		"6"
	}
	"ActivateReplaceColorButton"
	{
		"fieldName"		"ActivateReplaceColorButton"
		"xpos"		"235"
		"ypos"		"0"
		"wide"		"20"
		"tall"		"75"
		"ControlName"		"Panel"
		"image"		"swarm\color\hsv_slider_bar"
		"scaleImage"		"1"
		"zpos"		"5"
	}
	"Color1Button"
	{
		"fieldName"		"Color1Button"
		"xpos"		"265"
		"ypos"		"0"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
	}
	"Color2Button"
	{
		"fieldName"		"Color2Button"
		"xpos"		"285"
		"ypos"		"0"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
	}
	"Color3Button"
	{
		"fieldName"		"Color3Button"
		"xpos"		"305"
		"ypos"		"0"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
	}
	"Color4Button"
	{
		"fieldName"		"Color4Button"
		"xpos"		"265"
		"ypos"		"20"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
	}
	"Color5Button"
	{
		"fieldName"		"Color5Button"
		"xpos"		"285"
		"ypos"		"20"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
	}
	"Color6Button"
	{
		"fieldName"		"Color6Button"
		"xpos"		"305"
		"ypos"		"20"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
	}
	"Color7Button"
	{
		"fieldName"		"Color7Button"
		"xpos"		"265"
		"ypos"		"40"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
	}
	"Color8Button"
	{
		"fieldName"		"Color8Button"
		"xpos"		"285"
		"ypos"		"40"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
	}
	"Color9Button"
	{
		"fieldName"		"Color9Button"
		"xpos"		"305"
		"ypos"		"40"
		"wide"		"15"
		"tall"		"15"
		"ControlName"		"CBitmapButton"
		"zpos"		"5"
	}
}