"Resource/UI/NB_Select_Marine_Panel.res"
{
	"Select_Marine_Panel"
	{
		"fieldName"		"Select_Marine_Panel"
		"ControlName"		"EditablePanel"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"f0"
		"tall"		"f0"
		"zpos"		"50"
	}
	"Title"
	{
		"fieldName"		"Title"
		"xpos"		"c-210"
		"ypos"		"8"
		"wide"		"150"
		"tall"		"22"
		"zpos"		"5"
		"font"		"DefaultExtraLarge"
		"labelText"		"#nb_select_marine"
		"textAlignment"		"west"
		"ControlName"		"Label"
		"fgcolor_override"		"224 224 224 255"
	}
	"MarineNameLabel"
	{
		"fieldName"		"MarineNameLabel"
		"xpos"		"c-192"
		"ypos"		"280"
		"wide"		"160"
		"tall"		"17"
		"font"		"DefaultLarge"
		"textAlignment"		"center"
		"ControlName"		"Label"
		"fgcolor_override"		"83 148 192 255"
		"zpos" "5"
	}
	"BioTitle"
	{
		"fieldName"		"BioTitle"
		"xpos"		"c17"
		"ypos"		"300"
		"wide"		"71"
		"tall"		"12"
		"font"		"Default"
		"labelText"		"#nb_bio"
		"textAlignment"		"west"
		"ControlName"		"Label"
		"fgcolor_override"		"83 148 192 255"
		"zpos" "5"
	}
	"BioLabel"
	{
		"fieldName"		"BioLabel"
		"xpos"		"c17"
		"ypos"		"312"
		"wide"		"201"
		"tall"		"150"
		"font"		"Default"
		"labelText"		"BioLabel"
		"textAlignment"		"north-west"
		"ControlName"		"Label"
		"wrap"		"1"
		"fgcolor_override"		"83 148 192 255"
		"zpos" "5"
	}
	"AcceptButton"
	{
		"fieldName"		"AcceptButton"
		"xpos"		"c-140"
		"ypos"		"r23"
		"wide"		"117"
		"tall"		"27"
		"ControlName"		"CNB_Button"
		"textAlignment"		"center"
		"font"		"DefaultMedium"
		"fgcolor_override"		"113 142 181 255"
		"zpos"		"3"
		"labelText"		"#nb_accept"
		"visible"	"0"
	}
	"BackButton"
	{
		"fieldName"		"BackButton"
		"xpos"		"c-264"
		"ypos"		"r23"
		"wide"		"117"
		"tall"		"27"
		"ControlName"		"CNB_Button"
		"labelText"		"#nb_back"
		"textAlignment"		"center"
		"font"		"DefaultMedium"
		"fgcolor_override"		"113 142 181 255"
		"zpos"		"3"
	}
	"SkillPanel0"
	{
		"fieldName"		"SkillPanel0"
		"xpos"		"c-192"
		"ypos"		"300"
		"wide"		"160"
		"tall"		"25"
		"ControlName"		"CNB_Skill_Panel"
	}
	"SkillPanel1"
	{
		"fieldName"		"SkillPanel1"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"160"
		"tall"		"25"
		"ControlName"		"CNB_Skill_Panel"
		"pin_to_sibling"		"SkillPanel0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"2"
	}
	"SkillPanel2"
	{
		"fieldName"		"SkillPanel2"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"160"
		"tall"		"25"
		"ControlName"		"CNB_Skill_Panel"
		"pin_to_sibling"		"SkillPanel1"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"2"
	}
	"SkillPanel3"
	{
		"fieldName"		"SkillPanel3"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"160"
		"tall"		"25"
		"ControlName"		"CNB_Skill_Panel"
		"pin_to_sibling"		"SkillPanel2"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"2"
	}
	"SkillPanel4"
	{
		"fieldName"		"SkillPanel4"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"160"
		"tall"		"25"
		"ControlName"		"CNB_Skill_Panel"
		"pin_to_sibling"		"SkillPanel3"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"2"
	}
	"SkillPointsLabel"
	{
		"fieldName"		"SkillPointsLabel"
		"xpos"		"-10"
		"ypos"		"0"
		"wide"		"160"
		"tall"		"15"
		"ControlName"		"Label"
		"pin_to_sibling"		"SkillPanel4"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"2"
	}
	"PortraitsBackground"
	{
		"fieldName"		"PortraitsBackground"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"f0"
		"tall"		"116"
		"ControlName"		"ImagePanel"
		"image"		"briefing/select_marine_list_bg"
		"scaleImage"		"1"
		"zpos"		"2"
	}
	"PortraitsLowerBackground"
	{
		"fieldName"		"PortraitsLowerBackground"
		"xpos"		"0"
		"ypos"		"159"
		"wide"		"f0"
		"tall"		"116"
		"ControlName"		"ImagePanel"
		"image"		"briefing/select_marine_list_bg"
		"scaleImage"		"1"
		"zpos"		"2"
	}
}
