name: Continuous integration
on:
  push:
    branches:
      - reactivedrop_public
      - reactivedrop_beta
  pull_request:
    branches:
      - reactivedrop_public
      - reactivedrop_beta

# GitHub Actions usage is FREE for both public repositories and self-hosted runners.
# We can use it to build our project and do some automated builds and in future quality tests.
# https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

jobs:
  build:
    name: build ${{ matrix.configuration }}
    runs-on: windows-2025-vs2026
    timeout-minutes: 30
    strategy:
      matrix:
        configuration: [Release, Debug]

    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build server.dll
        working-directory: src/game/server
        run: MSBuild.exe swarm_sdk_server.vcxproj -property:Configuration=${{ matrix.configuration }} -property:Platform=Win32

      - name: Build client.dll
        working-directory: src/game/client
        run: MSBuild.exe swarm_sdk_client.vcxproj -property:Configuration=${{ matrix.configuration }} -property:Platform=Win32

      - name: Build missionchooser.dll
        working-directory: src/game/missionchooser
        run: MSBuild.exe swarm_sdk_missionchooser.vcxproj -property:Configuration=${{ matrix.configuration }} -property:Platform=Win32

      # make sure retention is low, this can become huge otherwise
      - name: Store build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configuration }}
          path: |
            reactivedrop/bin/server.dll
            reactivedrop/bin/client.dll
            reactivedrop/bin/missionchooser.dll
