name: Continuous integration
run-name: ${{ inputs.title }}

on:
  push:
    branches:
      - reactivedrop_public
      - reactivedrop_beta
  pull_request:
    branches:
      - reactivedrop_public
      - reactivedrop_beta
  workflow_dispatch:
    inputs:
      title:
        type: string
        default: Workflow dispatch
      configuration:
        description: "Configuration to build"
        required: true
        type: choice
        options:
          - Release
          - Debug
          - All
        default: All
      server:
        description: server.dll
        type: boolean
        default: true
      client:
        description: client.dll
        type: boolean
        default: true
      missionchooser:
        description: missionchooser.dll
        type: boolean
        default: true

# GitHub Actions usage is FREE for both public repositories and self-hosted runners.
# We can use it to build our project and do some automated builds and in future quality tests.
# https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

jobs:
  build:
    name: build ${{ matrix.configuration }}
    runs-on: windows-2025-vs2026
    timeout-minutes: 30
    strategy:
      matrix:
        configuration: ${{ fromJSON(
          (github.event_name != 'workflow_dispatch' || inputs.configuration == 'All')
            && '["Release","Debug"]'
            || format('["{0}"]', inputs.configuration)
          ) }}

    steps:
      - name: Validate workflow dispatch dll selection
        if: ${{ github.event_name == 'workflow_dispatch' && !inputs.server && !inputs.client && !inputs.missionchooser }}
        shell: bash
        run: |
          echo "::error::Select at least one dll to build."
          exit 1

      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build server.dll
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.server }}
        working-directory: src/game/server
        run: MSBuild.exe swarm_sdk_server.vcxproj -property:Configuration=${{ matrix.configuration }} -property:Platform=Win32

      - name: Build client.dll
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.client }}
        working-directory: src/game/client
        run: MSBuild.exe swarm_sdk_client.vcxproj -property:Configuration=${{ matrix.configuration }} -property:Platform=Win32

      - name: Build missionchooser.dll
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.missionchooser }}
        working-directory: src/game/missionchooser
        run: MSBuild.exe swarm_sdk_missionchooser.vcxproj -property:Configuration=${{ matrix.configuration }} -property:Platform=Win32

      # make sure retention is low, this can become huge otherwise
      - name: Store build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configuration }}
          path: |
            reactivedrop/bin/server.dll
            reactivedrop/bin/client.dll
            reactivedrop/bin/missionchooser.dll
